//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>

export type AcceptInviteError = 'NONE' | 'NOT_FOUND' | 'EXPIRED' | 'YOU_ARE_BANNED'
