//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>

interface IArchetypeDto
{
	Id: Guid;
	ServerId: Guid;
	Name: string;
	Description: string;
	IsMentionable: boolean;
	Colour: number;
	IsHidden: boolean;
	IsLocked: boolean;
	IsGroup: boolean;
	IconFileId?: string;
	Entitlement: string;
}
