//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="Argon/ArchetypeModel/IArchetype.d.ts"/>
///<reference path="IArgonEntityWithOwnership.d.ts"/>
///<reference path="IServerMemberArchetype.d.ts"/>

interface IArchetype extends Argon.ArchetypeModel.IArchetype, IArgonEntityWithOwnership
{
	Name: string;
	Description: string;
	Entitlement: number;
	Colour: any;
	IconFileId?: string;
	ServerMemberRoles: IServerMemberArchetype[];
}
