//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="IMessageEntity.d.ts"/>

interface IArgonMessageDto
{
	MessageId: number;
	ReplyId?: number;
	ChannelId: Guid;
	ServerId: Guid;
	Text: string;
	Entities: IMessageEntity[];
	TimeSent: number;
	Sender: Guid;
}
