//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="IArgonEntityWithOwnership.d.ts"/>
///<reference path="IMessageImage.d.ts"/>
///<reference path="IMessageEntity.d.ts"/>

interface IArgonMessage extends IArgonEntityWithOwnership
{
	ChannelId: Guid;
	ReplyToMessage?: Guid;
	Text: string;
	Document?: any;
	Image?: IMessageImage[];
	Sticker?: any;
	Entities: IMessageEntity[];
	IsEmpty() : boolean;
}
