//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="Argon/ArchetypeModel/IArchetypeObject.d.ts"/>
///<reference path="IArgonEntityWithOwnership.d.ts"/>
///<reference path="IChannelEntitlementOverwrite.d.ts"/>

interface IChannel extends Argon.ArchetypeModel.IArchetypeObject, IArgonEntityWithOwnership
{
	ChannelType: 'Announcement' | 'Voice' | 'Text';
	ServerId: Guid;
	Name: string;
	Description?: string;
	EntitlementOverwrites: IChannelEntitlementOverwrite[];
	Overwrites: any[];
}
