//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="Argon/ArchetypeModel/IArchetypeOverwrite.d.ts"/>
///<reference path="IArgonEntityWithOwnership.d.ts"/>
///<reference path="IArchetypeScope.d.ts"/>

interface IChannelEntitlementOverwrite extends Argon.ArchetypeModel.IArchetypeOverwrite, IArgonEntityWithOwnership
{
	ChannelId: Guid;
	Scope: IArchetypeScope;
	ArchetypeId?: Guid;
	ServerMemberId?: Guid;
	Allow: number;
	Deny: number;
}
