//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="Argon/ArchetypeModel/IArchetypeOverwrite.d.ts"/>
///<reference path="IArgonEntityWithOwnership.d.ts"/>

interface IChannelEntitlementOverwrite extends Argon.ArchetypeModel.IArchetypeOverwrite, IArgonEntityWithOwnership
{
	ChannelId: string;
	Scope: 'Archetype' | 'Member';
	ArchetypeId?: string;
	ServerMemberId?: string;
	Allow: number;
	Deny: number;
}
