//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="IArgonEntityWithOwnership.d.ts"/>

interface IMessageImage extends IArgonEntityWithOwnership
{
	MessageId: Guid;
	FileName: string;
	MimeType: string;
	IsVideo: boolean;
	FileId: string;
	Width: number;
	Height: number;
	FileSize: number;
}
