//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="InviteCode.d.ts"/>

interface InviteCodeEntity
{
	code: InviteCode;
	serverId: string;
	issuerId: string;
	expireTime: Date;
	used: number;
}
