//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="IArgonEntityWithOwnership.d.ts"/>
///<reference path="IUser.d.ts"/>
///<reference path="IServerMemberArchetype.d.ts"/>

interface IServerMember extends IArgonEntityWithOwnership
{
	ServerId: Guid;
	UserId: Guid;
	User: IUser;
	JoinedAt: Date;
	ServerMemberArchetypes: IServerMemberArchetype[];
}
