//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="IChannel.d.ts"/>
///<reference path="IServerMemberDto.d.ts"/>
///<reference path="IArchetype.d.ts"/>

interface IServerDto
{
	Id: Guid;
	Name: string;
	Description: string;
	AvatarFieldId: string;
	TopBannerFileId: string;
	Channels: IChannel[];
	Users: IServerMemberDto[];
	Archetypes: IArchetype[];
	Categories: any[];
}
