//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="IArgonEntity.d.ts"/>
///<reference path="IServerMember.d.ts"/>

interface IUser extends IArgonEntity
{
	Email: string;
	Username: string;
	DisplayName: string;
	PhoneNumber?: string;
	PasswordDigest?: string;
	AvatarFileId?: string;
	OtpHash?: string;
	ServerMembers: IServerMember[];
	LockdownReason: 'NONE' | 'SPAM_SCAM_ACCOUNT' | 'INCITING_MOMENT' | 'NON_BINARY_PERSON' | 'TOS_VIOLATION' | 'LGBT_AGITATION' | 'DRUG_VIOLATION' | 'TERRORISM_AGITATION' | 'CHILD_ABUSE';
	LockDownExpiration?: Date;
}
