//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="IServerMemberArchetypeDto.d.ts"/>

interface IUserProfileDto
{
	UserId: Guid;
	CustomStatus?: string;
	CustomStatusIconId?: string;
	BannerFileId?: string;
	DateOfBirth?: Date;
	Bio?: string;
	IsPremium: boolean;
	Badges: string[];
	Archetypes: IServerMemberArchetypeDto[];
}
