//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>
///<reference path="UserStatus.d.ts"/>
///<reference path="IUserNotificationSnapshot.d.ts"/>

interface WelcomeCommander extends IArgonEvent
{
	EventKey: 'WelcomeCommander';
	welcomeMessage: string;
	status: UserStatus;
	notifications: IUserNotificationSnapshot;
	Sequence: number;
	EventId: number;
}
