//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Guid.d.ts"/>
///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>

export type LockdownReason = 'NONE' | 'SPAM_SCAM_ACCOUNT' | 'INCITING_MOMENT' | 'NON_BINARY_PERSON' | 'TOS_VIOLATION' | 'LGBT_AGITATION' | 'DRUG_VIOLATION' | 'TERRORISM_AGITATION' | 'CHILD_ABUSE'
