//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

///<reference path="../Either.d.ts"/>
///<reference path="../Maybe.ts"/>

export type RegistrationError = 'USERNAME_ALREADY_TAKEN' | 'USERNAME_RESERVED' | 'EMAIL_ALREADY_REGISTERED' | 'REGION_BANNED' | 'EMAIL_BANNED' | 'SSO_EMAILS_NOT_ALLOWED' | 'INTERNAL_ERROR'
