//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export type ArgonEntitlementValue = { bit: bigint; key: string };
export const NONE: ArgonEntitlementValue = { key: "None", bit: BigInt("0") };
export const VIEWCHANNEL: ArgonEntitlementValue = {
  key: "ViewChannel",
  bit: BigInt("1"),
};
export const READHISTORY: ArgonEntitlementValue = {
  key: "ReadHistory",
  bit: BigInt("2"),
};
export const BASE: ArgonEntitlementValue = { key: "Base", bit: BigInt("3") };
export const JOINTOVOICE: ArgonEntitlementValue = {
  key: "JoinToVoice",
  bit: BigInt("4"),
};
export const SENDMESSAGES: ArgonEntitlementValue = {
  key: "SendMessages",
  bit: BigInt("32"),
};
export const SENDVOICE: ArgonEntitlementValue = {
  key: "SendVoice",
  bit: BigInt("64"),
};
export const ATTACHFILES: ArgonEntitlementValue = {
  key: "AttachFiles",
  bit: BigInt("128"),
};
export const ADDREACTIONS: ArgonEntitlementValue = {
  key: "AddReactions",
  bit: BigInt("256"),
};
export const ANYMENTIONS: ArgonEntitlementValue = {
  key: "AnyMentions",
  bit: BigInt("512"),
};
export const MENTIONEVERYONE: ArgonEntitlementValue = {
  key: "MentionEveryone",
  bit: BigInt("1024"),
};
export const EXTERNALEMOJI: ArgonEntitlementValue = {
  key: "ExternalEmoji",
  bit: BigInt("2048"),
};
export const EXTERNALSTICKERS: ArgonEntitlementValue = {
  key: "ExternalStickers",
  bit: BigInt("4096"),
};
export const USECOMMANDS: ArgonEntitlementValue = {
  key: "UseCommands",
  bit: BigInt("8192"),
};
export const POSTEMBEDDEDLINKS: ArgonEntitlementValue = {
  key: "PostEmbeddedLinks",
  bit: BigInt("16384"),
};
export const BASECHAT: ArgonEntitlementValue = {
  key: "BaseChat",
  bit: BigInt("31712"),
};
export const CONNECT: ArgonEntitlementValue = {
  key: "Connect",
  bit: BigInt("1048576"),
};
export const SPEAK: ArgonEntitlementValue = {
  key: "Speak",
  bit: BigInt("2097152"),
};
export const VIDEO: ArgonEntitlementValue = {
  key: "Video",
  bit: BigInt("4194304"),
};
export const STREAM: ArgonEntitlementValue = {
  key: "Stream",
  bit: BigInt("8388608"),
};
export const BASEMEDIA: ArgonEntitlementValue = {
  key: "BaseMedia",
  bit: BigInt("15728640"),
};
export const BASEMEMBER: ArgonEntitlementValue = {
  key: "BaseMember",
  bit: BigInt("15760355"),
};
export const USEASIO: ArgonEntitlementValue = {
  key: "UseASIO",
  bit: BigInt("1073741824"),
};
export const ADDITIONALSTREAMS: ArgonEntitlementValue = {
  key: "AdditionalStreams",
  bit: BigInt("2147483648"),
};
export const BASEEXTENDED: ArgonEntitlementValue = {
  key: "BaseExtended",
  bit: BigInt("3221225472"),
};
export const DISCONNECTMEMBER: ArgonEntitlementValue = {
  key: "DisconnectMember",
  bit: BigInt("1099511627776"),
};
export const MOVEMEMBER: ArgonEntitlementValue = {
  key: "MoveMember",
  bit: BigInt("2199023255552"),
};
export const BANMEMBER: ArgonEntitlementValue = {
  key: "BanMember",
  bit: BigInt("4398046511104"),
};
export const MUTEMEMBER: ArgonEntitlementValue = {
  key: "MuteMember",
  bit: BigInt("8796093022208"),
};
export const KICKMEMBER: ArgonEntitlementValue = {
  key: "KickMember",
  bit: BigInt("17592186044416"),
};
export const MODERATEMEMBERS: ArgonEntitlementValue = {
  key: "ModerateMembers",
  bit: BigInt("34084860461056"),
};
export const MANAGECHANNELS: ArgonEntitlementValue = {
  key: "ManageChannels",
  bit: BigInt("1125899906842624"),
};
export const MANAGEARCHETYPE: ArgonEntitlementValue = {
  key: "ManageArchetype",
  bit: BigInt("2251799813685248"),
};
export const MANAGEBOTS: ArgonEntitlementValue = {
  key: "ManageBots",
  bit: BigInt("4503599627370496"),
};
export const MANAGEEVENTS: ArgonEntitlementValue = {
  key: "ManageEvents",
  bit: BigInt("9007199254740992"),
};
export const MANAGEBEHAVIOUR: ArgonEntitlementValue = {
  key: "ManageBehaviour",
  bit: BigInt("18014398509481984"),
};
export const MANAGESERVER: ArgonEntitlementValue = {
  key: "ManageServer",
  bit: BigInt("36028797018963968"),
};
export const CONTROLSERVER: ArgonEntitlementValue = {
  key: "ControlServer",
  bit: BigInt("70931694131085312"),
};
export const ADMINISTRATOR: ArgonEntitlementValue = {
  key: "Administrator",
  bit: BigInt("18446744073709551615"),
};
export const ALL_ENTITLEMENT: ArgonEntitlementValue[] = [
  NONE,
  VIEWCHANNEL,
  READHISTORY,
  BASE,
  JOINTOVOICE,
  SENDMESSAGES,
  SENDVOICE,
  ATTACHFILES,
  ADDREACTIONS,
  ANYMENTIONS,
  MENTIONEVERYONE,
  EXTERNALEMOJI,
  EXTERNALSTICKERS,
  USECOMMANDS,
  POSTEMBEDDEDLINKS,
  BASECHAT,
  CONNECT,
  SPEAK,
  VIDEO,
  STREAM,
  BASEMEDIA,
  BASEMEMBER,
  USEASIO,
  ADDITIONALSTREAMS,
  BASEEXTENDED,
  DISCONNECTMEMBER,
  MOVEMEMBER,
  BANMEMBER,
  MUTEMEMBER,
  KICKMEMBER,
  MODERATEMEMBERS,
  MANAGECHANNELS,
  MANAGEARCHETYPE,
  MANAGEBOTS,
  MANAGEEVENTS,
  MANAGEBEHAVIOUR,
  MANAGESERVER,
  CONTROLSERVER,
  ADMINISTRATOR,
];
export type ArgonEntitlement =
  | "None"
  | "ViewChannel"
  | "ReadHistory"
  | "Base"
  | "JoinToVoice"
  | "SendMessages"
  | "SendVoice"
  | "AttachFiles"
  | "AddReactions"
  | "AnyMentions"
  | "MentionEveryone"
  | "ExternalEmoji"
  | "ExternalStickers"
  | "UseCommands"
  | "PostEmbeddedLinks"
  | "BaseChat"
  | "Connect"
  | "Speak"
  | "Video"
  | "Stream"
  | "BaseMedia"
  | "BaseMember"
  | "UseASIO"
  | "AdditionalStreams"
  | "BaseExtended"
  | "DisconnectMember"
  | "MoveMember"
  | "BanMember"
  | "MuteMember"
  | "KickMember"
  | "ModerateMembers"
  | "ManageChannels"
  | "ManageArchetype"
  | "ManageBots"
  | "ManageEvents"
  | "ManageBehaviour"
  | "ManageServer"
  | "ControlServer"
  | "Administrator";
