// <auto-generated by adigen — DO NOT EDIT; regenerate with `dotnet run --project tools/adigen -- ts` />
// Typed renderer client for native plugin services exposed over argon:rpc
// (window.argonIpc.invoke). Source of truth: C# [ArgonExport(Expose = Renderer)].
/* eslint-disable */

/** A media session's current track + playback state. */
export interface MediaTrackInfo {
  sessionId: string;
  title: string;
  author: string;
  isPlaying: boolean;
}

/** User idle time snapshot. */
export interface IdleTimeInfo {
  idleMs: number;
}

/** Native plugin `audio` (libaml). */
export interface IAudioNative {
  /** Returns the currently playing track, or null when nothing is playing. */
  getCurrentTrack(): Promise<MediaTrackInfo | null>;
}

/** Native plugin `idle` (libaidl). */
export interface IIdleNative {
  /** Returns how long the user has been idle, in milliseconds. */
  getIdleTime(): Promise<IdleTimeInfo | null>;
}

function service<T>(name: string): T {
  return new Proxy({} as Record<string, unknown>, {
    get: (_target, method: string) => (...args: unknown[]) =>
      (window as any).argonIpc.invoke(name, method, args),
  }) as unknown as T;
}

export const AudioNative = service<IAudioNative>('AudioNative');
export const IdleNative = service<IIdleNative>('IdleNative');
