import { defineConfig } from "vitest/config";
import vue from "@vitejs/plugin-vue";
import { playwright } from "@vitest/browser-playwright";
import tailwind from "tailwindcss";
import autoprefixer from "autoprefixer";
import path from "node:path";

/**
 * Runs the app's own tests plus every package that ships its own vitest config.
 *
 * Packages are listed as projects rather than swept into one include glob: each is
 * expected to be extractable into its own repository, so its tests have to run from
 * its own directory with its own config. This root config only aggregates them.
 *
 * Standalone on purpose otherwise — vite.config.ts carries app-only concerns (dev https
 * certs, Sentry upload, devtools) that have no business running in tests.
 */
export default defineConfig({
  test: {
    coverage: {
      provider: "v8",
      // Packages only. The app's src/ is overwhelmingly Vue components whose value is
      // in how they look and feel, not in branch coverage; the packages are the
      // reusable logic, and they are what a coverage number should describe.
      include: ["packages/*/src/**/*.ts"],
      exclude: [
        "**/*.g.ts",
        "**/*.d.ts",
        // Only the top-level barrel — a nested index.ts is real implementation
        // (packages/core/src/disposables/index.ts is the DisposableBag itself).
        "packages/*/src/index.ts",
        // Machine-written: ion codegen emits these with an <auto-generated> header and
        // they are regenerated wholesale, so tests over them would assert the generator.
        "packages/glue/src/argonChat.ts",
        "packages/glue/src/argon.ipc.ts",
        // Covered by `bun test playframe` (86% lines) — counting them here as zero
        // would understate the suite rather than describe it.
        "packages/playframe*/src/**",
      ],
      reporter: ["text", "json-summary"],
    },
    projects: [
      {
        plugins: [vue()],
        resolve: {
          alias: { "@": path.resolve(__dirname, "./src") },
        },
        test: {
          name: "app",
          environment: "happy-dom",
          include: ["test/**/*.test.ts"],
          exclude: ["test/browser/**"],
          globals: false,
          restoreMocks: true,
        },
      },
      // What only a real browser answers honestly: layout, scrolling, ResizeObserver. happy-dom
      // computes none of it, and a faked geometry can hide a bug as easily as invent one.
      {
        plugins: [vue()],
        resolve: {
          alias: { "@": path.resolve(__dirname, "./src") },
        },
        // The app's stylesheet, so what is laid out is what the app lays out.
        css: { postcss: { plugins: [tailwind(), autoprefixer()] } },
        test: {
          name: "browser",
          include: ["test/browser/**/*.test.ts"],
          globals: false,
          restoreMocks: true,
          browser: {
            enabled: true,
            provider: playwright(),
            headless: true,
            instances: [{ browser: "chromium" }],
          },
        },
      },
      "packages/*/vitest.config.ts",
    ],
  },
});
