// Legal version comparison. Versions are plain DD.MM.YYYY date strings produced
// by the landing (the source of truth) and copied into src/legal/generated by
// scripts/sync-legal.ts. The server stores which version the user last accepted;
// the client owns the "current" version and decides when to force re-acceptance.

/** Parse a DD.MM.YYYY legal version into a comparable UTC timestamp, or null if invalid. */
export function parseLegalVersion(v: string | null | undefined): number | null {
  if (!v) return null;
  const m = /^(\d{2})\.(\d{2})\.(\d{4})$/.exec(v.trim());
  if (!m) return null;
  const [, dd, mm, yyyy] = m;
  return Date.UTC(Number(yyyy), Number(mm) - 1, Number(dd));
}

/**
 * True when the user must (re-)accept: they never accepted (or the stored value is
 * unparseable), or their accepted date is older than the current one.
 */
export function isLegalOutdated(accepted: string | null | undefined, current: string): boolean {
  const c = parseLegalVersion(current);
  if (c === null) return false; // no/invalid current version → nothing to enforce
  const a = parseLegalVersion(accepted);
  if (a === null) return true; // never accepted → outdated
  return a < c;
}
