/**
 * Sync legal documents from the landing (source of truth) into the client.
 *
 * The landing owns the legal content as shared, native Vue components
 * (landing/src/legal/{TermsBody,PrivacyBody}.vue) plus the current versions
 * (landing/src/legal/versions.ts) and the styling (landing/src/styles/legal.css).
 * This script copies them into client/src/legal/generated/ as date-versioned
 * templates so the client can render the latest TOS/Privacy in a modal and
 * compare the user's accepted version against the current one.
 *
 *   bun run scripts/sync-legal.ts        # copy current landing legal into the client
 *
 * Output (committed, like the ion glue and the games bundles):
 *   client/src/legal/generated/terms/<version>.vue      (dated history)
 *   client/src/legal/generated/privacy/<version>.vue
 *   client/src/legal/generated/legal.css                (dark-only, self-contained)
 *   client/src/legal/generated/index.ts                 (LEGAL manifest → current)
 *
 * Re-run whenever a *Body.vue or the version changes, then commit the result.
 * The client build does NOT run this (it would couple the client to the landing
 * folder); the generated files are the contract.
 */

import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const root = resolve(import.meta.dir, "..");
const landingLegal = resolve(root, "..", "landing", "src", "legal");
const landingStyles = resolve(root, "..", "landing", "src", "styles");
const outDir = resolve(root, "src", "legal", "generated");

// Dark theme values, mirrored from landing/src/styles/global.css @theme. The
// shared legal.css uses these --color-* vars; on the landing they resolve from
// the global theme, in the client we pin them on the .legal-doc wrapper so the
// modal renders identically (always dark) regardless of the client's theme.
const DARK_VARS = `.legal-doc {
  --color-text-primary: #ebebeb;
  --color-text-secondary: #9a9a9a;
  --color-text-muted: #737373;
  --color-accent: #8b5cf6;
  --color-accent-hover: #a78bfa;
  --color-accent-subtle: rgba(139, 92, 246, 0.12);
  --color-oled-surface: #080808;
  --color-oled-border: #222222;
  --color-oled-border-subtle: #181818;
  --color-success: #34d399;
}
`;

const STRIP_START = "/* @client-strip-start";
const STRIP_END = "@client-strip-end */";

// Remove the landing-only light-mode block so the client copy is dark-only.
function stripLightBlock(css: string): string {
  const s = css.indexOf(STRIP_START);
  const e = css.indexOf(STRIP_END);
  if (s === -1 || e === -1) return css;
  return css.slice(0, s).trimEnd() + "\n\n" + css.slice(e + STRIP_END.length).trimStart();
}

const DOCS = [
  { key: "terms", body: "TermsBody.vue", ident: "TermsCurrent" },
  { key: "privacy", body: "PrivacyBody.vue", ident: "PrivacyCurrent" },
] as const;

async function main(): Promise<void> {
  // 1. Current versions (source of truth).
  const { LEGAL_VERSIONS } = await import(pathToFileURL(resolve(landingLegal, "versions.ts")).href);
  for (const { key } of DOCS) {
    const v = LEGAL_VERSIONS?.[key];
    if (typeof v !== "string" || !/^\d{2}\.\d{2}\.\d{4}$/.test(v)) {
      console.error(`[sync-legal] versions.ts: ${key} must be a DD.MM.YYYY string, got ${JSON.stringify(v)}`);
      process.exit(1);
    }
  }

  // 2. Copy each document body verbatim into a date-named file (history accrues).
  for (const { key, body } of DOCS) {
    const version: string = LEGAL_VERSIONS[key];
    const src = await Bun.file(resolve(landingLegal, body)).text();
    if (!src.includes('class="legal-prose"')) {
      console.error(`[sync-legal] ${body}: missing .legal-prose root — refusing to write`);
      process.exit(1);
    }
    const out = resolve(outDir, key, `${version}.vue`);
    await Bun.write(out, src);
    console.log(`[sync-legal] ${key} ${version} -> src/legal/generated/${key}/${version}.vue`);
  }

  // 3. Copy styling, transformed to a self-contained dark-only sheet.
  const css = await Bun.file(resolve(landingStyles, "legal.css")).text();
  const clientCss =
    `/* AUTO-GENERATED by scripts/sync-legal.ts from landing/src/styles/legal.css — do not edit. */\n\n` +
    DARK_VARS + "\n" + stripLightBlock(css);
  await Bun.write(resolve(outDir, "legal.css"), clientCss);

  // 4. Manifest: static imports so Vite bundles the current templates + styles.
  const imports = DOCS.map(({ key, ident }) => `import ${ident} from "./${key}/${LEGAL_VERSIONS[key]}.vue";`).join("\n");
  const entries = DOCS.map(({ key, ident }) => `  ${key}: { current: "${LEGAL_VERSIONS[key]}", component: ${ident} },`).join("\n");
  const index =
    `// AUTO-GENERATED by scripts/sync-legal.ts — do not edit by hand.\n` +
    `// Run \`bun run sync:legal\` after changing the landing legal documents.\n` +
    `import type { Component } from "vue";\n` +
    `import "./legal.css";\n` +
    `${imports}\n\n` +
    `export type LegalDoc = "terms" | "privacy";\n` +
    `export interface LegalEntry {\n  /** Current version, DD.MM.YYYY. */\n  current: string;\n  /** Renderable document body. */\n  component: Component;\n}\n\n` +
    `export const LEGAL: Record<LegalDoc, LegalEntry> = {\n${entries}\n};\n`;
  await Bun.write(resolve(outDir, "index.ts"), index);
  console.log(`[sync-legal] manifest -> src/legal/generated/index.ts`);
}

await main();
