// <auto-generated/>
// DO NOT TOUCH THIS FUCKING FILE, PROXY PROJECT REQUIRED FOR FUCKING ACCESS TO ORDERING OF PROJECTS (codegen not implemented this feature)
// </auto-generated>
namespace Argon.Glue;
using System.Threading.Tasks;
using System.Runtime.InteropServices.JavaScript;
using Argon.Glue;
using Argon.Contracts;
using Argon.Glue.Core;
public static partial class UserAuthorization
{

    [JSExport]
    [return: JSMarshalAs<JSType.Promise<JSType.Object>>]
    public static Task<JSObject> AuthorizeAsync([JSMarshalAs<JSType.Object>] JSObject request) =>
        Interop.DoCall<Argon.Contracts.AuthorizeResponse, AuthorizeRequest, IUserAuthorization>(
            (@interface, @in) => @interface.AuthorizeAsync(@in), request);

}
