// <auto-generated/>
// DO NOT TOUCH THIS FUCKING FILE, PROXY PROJECT REQUIRED FOR FUCKING ACCESS TO ORDERING OF PROJECTS (codegen not implemented this feature)
// </auto-generated>
namespace Argon.Glue;
using System.Threading.Tasks;
using System.Runtime.InteropServices.JavaScript;
using Argon.Glue;
using Argon.Contracts;
using Argon.Glue.Core;
public static partial class UserInteraction
{

    [JSExport]
    [return: JSMarshalAs<JSType.Promise<JSType.Object>>]
    public static Task<JSObject> GetMe() =>
        Interop.DoCall<Argon.Contracts.UserResponse, IUserInteraction>(
            (@interface) => @interface.GetMe());


    [JSExport]
    [return: JSMarshalAs<JSType.Promise<JSType.Object>>]
    public static Task<JSObject> CreateServer([JSMarshalAs<JSType.Object>] JSObject request) =>
        Interop.DoCall<Argon.Contracts.ServerResponse, CreateServerRequest, IUserInteraction>(
            (@interface, @in) => @interface.CreateServer(@in), request);


    [JSExport]
    [return: JSMarshalAs<JSType.Promise<JSType.Object>>]
    public static Task<JSObject> GetServers() =>
        Interop.DoCall<System.Collections.Generic.List<Argon.Contracts.ServerResponse>, IUserInteraction>(
            (@interface) => @interface.GetServers());


    [JSExport]
    [return: JSMarshalAs<JSType.Promise<JSType.Object>>]
    public static Task<JSObject> GetServerDetails([JSMarshalAs<JSType.Object>] JSObject request) =>
        Interop.DoCall<System.Collections.Generic.List<Argon.Contracts.ServerDetailsResponse>, ServerDetailsRequest, IUserInteraction>(
            (@interface, @in) => @interface.GetServerDetails(@in), request);


    [JSExport]
    [return: JSMarshalAs<JSType.Promise<JSType.Object>>]
    public static Task<JSObject> JoinChannel([JSMarshalAs<JSType.Object>] JSObject request) =>
        Interop.DoCall<Argon.Contracts.ChannelJoinResponse, ChannelJoinRequest, IUserInteraction>(
            (@interface, @in) => @interface.JoinChannel(@in), request);

}
