// @argon/glue - Generated API client and IPC types
// Auto-generated by IonPath Codegen - do not edit manually

// Main API client
export { createClient } from "./argonChat";
export * from "./argonChat";

// IPC types (for native apps)
export { createClient as createIpcClient } from "./argon.ipc";
export * from "./argon.ipc";

// Native glue
export { native, argon } from "./nativeGlue";
